services:
  hf-executor:
    extends:
      file: executor_base.yaml
      service: executor-base
    depends_on:
      - executor-builder
    environment:
      EXECUTOR_TYPE: huggingface
      EXECUTOR_ACCESS_CODE: gemma-7b-it
      EXECUTOR_NAME: Google Gemma 7B Instruct
      EXECUTOR_IMAGE: huggingface.svg # Refer to src/multi-chat/public/images
      HUGGING_FACE_HUB_TOKEN: ${HUGGING_FACE_HUB_TOKEN}
      TRANSFORMERS_OFFLINE: ${TRANSFORMERS_OFFLINE:-0}
    command: ["--model_path", "google/gemma-7b-it", "--no_system_prompt"]