services:
  rag-executor:
    extends:
      file: executor_base.yaml
      service: executor-base
    depends_on:
      - executor-builder
    environment:
      CUSTOM_EXECUTOR_PATH: ./docqa/docqa.py
      EXECUTOR_ACCESS_CODE: .tool/kuwa/rag
      EXECUTOR_NAME: RAG
      EXECUTOR_IMAGE: loupe.png # Refer to src/multi-chat/public/images
      EXECUTOR_ORDER: 990000
      EXECUTOR_CREATE_BOT: false
      TRANSFORMERS_OFFLINE: ${TRANSFORMERS_OFFLINE:-0} # For embedding model
    command: [
      "--api_base_url", "http://web/",
      "--model", ".bot/.default",
      "--log", "debug"
      ]